### ISSUE TITLE
DocumentHandler - Permanent Drawer Option

### ISSUE THREAD

**Issue by OlofSvahnVbg** [hajkmap/Hajk#1316]
Users have requested that the drawer should always be showing in desktop mode. Like this:

![image](https://user-images.githubusercontent.com/111860819/230360019-1878c7ba-71e2-4fec-b40a-c37cdc516a48.png) 

The lock option for the drawer menu should also be removed if the drawer is always showing. The same goes for the togglebutton, both shown below:

![image](https://user-images.githubusercontent.com/111860819/230360350-e1101398-afcf-4dec-aa80-85eecf5091e1.png)
![image](https://user-images.githubusercontent.com/111860819/230360043-b0cfaabd-dd79-4fc5-91f6-eab021726da9.png)

I suggest doing this by adding an option in admin for making the drawer permanent.

![image](https://user-images.githubusercontent.com/111860819/230360062-198807cb-5e73-40a8-a920-4e49850a2725.png)
 
In the code, there already exists a variable named “drawerPermanent”. This name, in my opinion, suggests that the drawer is permanent (always showing). But this is not the case, as the variable controls the “Låt sidopanelen vara last vid start”.
So, maybe we should change the name of that variable to “drawerLockedOnStart” and add the new variable and name it “drawerPermanent”.

Or we could add the new variable and name it “drawerAlwaysPermanent” or something, maybe that’s easier.

**Comment by jacobwod** [comment]
Sure, but keep in mind that this will probably be a move away from the principle of Material Design where the drawer usually is a collapsable side panel (Google "material design dashboard" for typical use cases of the Drawer).

That's also one of the principles, as [described in the official documentation](https://m2.material.io/components/navigation-drawer#usage): 
![image](https://user-images.githubusercontent.com/110222/231096422-c4929803-23af-4c19-bba5-2b629d8ca054.png)

On the other hand though, the same documentations says that
> Standard drawers **can be permanently visible or opened and closed by tapping** a navigation menu icon. They can be used on tablet and desktop only. On mobile, modal drawers are used instead.

So it looks like it's okay after all, but please [read up on the specification](https://m2.material.io/components/navigation-drawe) before implementing any changes.

**Comment by Hallbergs** [comment]
I agree that the `drawerPermanent`-setting should work as you described (a drawer that cannot be hidden). Changing `drawerPermanent` to `drawerLockedOnStart` and adding the new behavior to `drawerPermanent` sounds like the proper solution imo!

If/when you implement this, make sure to check eventual side-effects that might occur since `drawerPermanent` is probably stored in localStorage.

**Comment by Hallbergs** [comment]
Haha, as long as it is documented/commented on how they work somewhere it is fine!

**Comment by jacobwod** [comment]
BTW, just mentioning that the current solution _is_ a mess. If I recall correctly, in addition to the settings you mention, we have another set of settings that specify the mobile-only behaviour. Make sure to check them out and – most importantly – test on small-screen devices.

**Comment by jacobwod** [comment]
I did some more testing  and I'm not sure we can release this in 3.13. The thing is that **if this option is enabled, there is now way to switch between the different content types in Drawer**. Keep in mind that certain maps (like https://framtidsplan2050.halmstad.se) use Drawer to display contents from both the Tools menu _and_ DocumentHandler. (There are also ideas about displaying legend graphic in a third tab in Drawer.)

So, enabling this option removes also these buttons:
![Skärmavbild 2023-06-29 kl  14 56 13](https://github.com/hajkmap/Hajk/assets/110222/dddd4eb1-a4fc-4c1b-a7d7-661c2d4162e8)

Which unfortunately breaks certain map configurations and user are stuck in this view: 
![Skärmavbild 2023-06-29 kl  14 58 03](https://github.com/hajkmap/Hajk/assets/110222/a6ea4e9c-eb7f-4c39-be1b-2943836d1619)

I can see where it would be desirable to use this option (e.g. don't allow hiding the Drawer) but still be able to switch between Drawer content. 

What are your opinions, @OlofSvahnVbg, @Hallbergs, @jesade-vbg?

**Comment by jesade-vbg** [comment]
Ok, I see. We use this in ÖP & FÖP and we only have a few tools as control buttons and layermenu as widget. So we never use diffrent content types in the drawer as it is right now. If you have multiple drawer content it would probably be a good idea to be able to switch as you say..... yes. Only the "[X] button" and the Padlock should be hidden if Im thinking correctly. Maybe theres more forgotten scenarios....

**Comment by jacobwod** [comment]
That's right, but it's not just the cross (X) on the button that closes - it's the entire button (where the icon changes to a cross to visualise that "that's what you see now, click to close"). Kind of a toggle button. 

But otherwise that's correct: we should not hide the buttons, rather just hide the padlock AND remove the closing functionality from buttons. User should still be able to click the other button to show its contents in Drawer. Clicking on the _active_ button should not have any action in this case.

On a second thought, I realise that this might be weird in configurations where only one button exists. That means user will see a button but it will not have any action at all. Could be ok, but could also be confusing. I think we need to test and see. If it's confusing, then the last solution I have is to hide the button (if only one is visible), otherwise show buttons but remove click functionality on currently active. 😄
