### ISSUE TITLE
Infoclick on invisible layers

### ISSUE THREAD

**Issue by OlofSvahnVbg** [hajkmap/Hajk#1348]
Infoclick works even when a layer is turned off.

If you turn on a layer that is only visible on certain scales the infoclick still works on the scales where the layer is invisible. 
Se video below:
https://github.com/hajkmap/Hajk/assets/111860819/1a5e04ce-bce5-429a-a37f-29d6fac58f3d

To reproduce:
1. Go to https://karta.varberg.se/
2. Turn on "Fastighet, gräns och beteckning".
3. Zoom in until layer is visible.
4. Testclick on any property, and the info window will appear: ![image](https://github.com/hajkmap/Hajk/assets/111860819/3686d999-3683-4f2f-9711-8991f4b1502d)
5. Close the info window.
6. Zoom out to a scale where the layer is NOT visible.
7. Click on the map, and the info window will still appear: 
![image](https://github.com/hajkmap/Hajk/assets/111860819/7cf2f082-b97b-468e-8b92-5431b63c63d6)

The infoclick should no work on an invisible layer. No info window should appear.

To fix this we might be able to control infoclick so that it's only clickable on a layer that is visible.

**Comment by OlofSvahnVbg** [comment]
This minor change seems to work, however, may not be soild:

![image](https://github.com/hajkmap/Hajk/assets/111860819/3cd673b1-2215-47cc-aa3a-a05eea92671d)

Thoughts?

**Comment by jacobwod** [comment]
I'm not sure where this code snippet is located. But two thoughts:
- this should be done in the "model" (I recon we have such a thing, could be the MapClickModel that handles this? There's a lot of stuff there going on that filters out unwanted stuff (we literally use `.filter()` method on the `OL Layer` objects)). If that's where your code is - that's fine. If not - I think it should be placed there.
- There may be more reasons for a layer being invisible. The obvious one I think of is `opacity=0`. Please see how that behaves: if we're fixing "clicking on invisible because of zoom", we should also fix "invisible because of opacity". 

Thanks!

**Comment by OlofSvahnVbg** [comment]
This fix is in the `MapClickModel`, in the `#query` method.

**Comment by OlofSvahnVbg** [comment]
Yeah, I agree. The problem is that the logic for layer visibility seems to have a different tolerance for minZoom. The layer turns invisible when currentzoom is above minZoom, not equal, which (I think) is the cause for the bug.

I'll investigate on the "other end".

**Comment by Hallbergs** [comment]
I think OL shows layers when the zoom is less than _or equal to_ `maxZoom`. `minZoom` is handled differently (for some reason) - OL shows layers when the zoom is greater than `minZoom`.

If i understood OL correctly, the fix should be:
```js
if (
      layer.layersInfo &&
      layer.getMinZoom() < currentZoom &&
      currentZoom <= layer.getMaxZoom()
    )

**Comment by OlofSvahnVbg** [comment]
I think @Hallbergs solution could work fine. Note that the change needs to be implemented in `MapClickModel` and `Click`.

**Comment by Hallbergs** [comment]
Yes we have to make sure to add the change in both! :)

**Comment by jacobwod** [comment]
Excellent, go for it!
