### ISSUE TITLE
Sketch plugin: Rotate drawn objects

### ISSUE THREAD

**Issue by jesade-vbg** [hajkmap/Hajk#1455]
It would be great if it was possible to rotate drawn objects.

For example: You draw a house using Rectangle and then rotate it correctly in place (Perhaps checking for a good place for Attefall or Friggebod?).

Today its pretty hard to do correctly and you have to use the polygon tool.

Note that I have not thought much about how and where in GUI.

**Comment by jacobwod** [comment]
Sounds pretty reasonable. 

Regarding how to trigger this from the UI, I see there are mainly two options:
a. "advanced" tools usually do this using a modifier key. So we'd use say `Shift` to trigger this instead of the usual move interaction
b. an "easier" option, for users less experienced is to expose this functionality as an own button

**Comment by jesade-vbg** [comment]
Progress: Button and input sollution (not shift trigger for diffrent reasons).
Currently works great and only took a few hours between todays meetings.
Also features "click and hold" to rotate continuously.

![image](https://github.com/hajkmap/Hajk/assets/73874338/4e3d4ce1-8bf2-4dfd-acdc-ede592e8eeac)

**Comment by jesade-vbg** [comment]
https://github.com/hajkmap/Hajk/assets/73874338/f82a35c0-e77d-4a33-b1d0-ee70b3faea70

**Comment by Hallbergs** [comment]
Fantastic! 🥳
