### ISSUE TITLE
MapSwitcher keeping X,Y location of presented dataset

### ISSUE THREAD

**Issue by JakubPelka** [hajkmap/Hajk#351]
**Left to do:**
Currently this is checked in, but we should add an option in admin that makes this configurable. If option is activated, X and Y should be kept. Otherwise, they should be ignored when switching maps. 

**Original issue:**
Hello,
I’d like to suggest one solution that may improve the usage experience of HAJK.

Today if a person would like to compare data on two different maps (for example with archive ÖP and any other up to date map) than has to open two browser windows with HAJK and compare data (try to have same zoom level and location). And that will not be exactly the same map due to human error. I personally find it difficult and not very user friendly. 

I’d like to suggest that if you use MapSwitcher component it will switch map content but will keep the last x,y location information, so the map will reload on exact same place. Then jumping between different maps and datasets will be much easier. Eventually the other solution to mentioned problem (but probably not so easy to do) is to add possibility to use 2 different maps at the same time with transparency defined by user, but I’d rather stay with that first proposition as it seems easier to do. 

Hope you will find my idea worth concerning and discussing. 
Have a good day,
Jakub Pelka, Halmstads Kommun

**Comment by jacobwod** [comment]
Not impossible to solve, if we decide that this is the wanted behavior:

onClick in MapSwitcher:
1. Get ol.View's center coordinate and current zoom level, save 
1. Append saved values to `url` when we do `window.location = ${url}` in `MapSwitcher`

Opinions?

**Comment by perosoderstrom** [comment]
Good idea. I would prefer, as Jakub suggests, that the map you switch to opens in current position and zoom. 
This needs however a check in Mapswitcher that the area is within the map extent, if the maps don't fully overlap (although for a municipality they normally do).

Possible work around: To get the same position and zoom, use the search tool with the same search object (if applicable) and then the Zoom In/Zoom Out-buttons. Do not pan with the mouse. By that you avoid the human factor.

**Comment by jacobwod** [comment]
> This needs however a check in Mapswitcher that the area is within the map extent, if the maps don't fully overlap (although for a municipality they normally do).
Important suggestion!

Should be possible to check what would happen even now, before we start working on it: supply an out-of-boundary coordinate as `x` and `y` in URL and see if the map loads there or in the point closest to that, but within extent.

**Comment by perosoderstrom** [comment]
I made a quick check with Dela länk. x=0, y=. It loads the map within the extent and close to 0,0, as it "at least tried"-

**Comment by jacobwod** [comment]
Thank you for checking @perosoderstrom. So, one idea would be to **show a Snackbar to the user and inform that the requested coordinates are outside the current map's extent**.

**Comment by perosoderstrom** [comment]
Good to inform the user, and if the coordinates are outside the extent, I think it would be best to open the map  with the defaiult origin.

**Comment by jacobwod** [comment]
I agree. Ending up in some random place that happens to be the closest point to the defined coordinate is not good enough and will only lead to confusion.

**Comment by jacobwod** [comment]
I'm on this, but I just figured that it won't be possible to "compare different datasets", because we can not grab visible layer's `ids` with us between different maps. The reason for this is that we can not be certain that any given layer that was present in one map configuration will be present in another. 

Regarding coordinates and zoom level: sure, we can keep them. But you will end up in a plain map each time anyway and will need to activate desired layers.

**Comment by jacobwod** [comment]
There are further problems with this approach: 
- It requires that map configs that we switch between have the same amount of zoom levels, and
- that the zoom levels are bound to same resolutions.

Otherwise, just sending in, `x` and `z` plus e.g. `z=5` can show completely different views, if zoom levels do not correspond. 

Another problem is:
- how can we "get back" to a "start view", as if page was reloaded with none extra parameters?
We can't, because we process the extra `x`, `y` and `z` on load and override hard-coded mapconfig defaults with values from param. So there isn't even a "way out" of this, if user would want to "reset".

**Comment by jacobwod** [comment]
During the latest meeting we decided that this should be an option, configurable in the admin UI.
