### ISSUE TITLE
Infoclick admin options don't do anything

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#356]
# Problem
Infoclick can be configured in `admin` among (confusingly) other plugins (even though it's not in `/plugin` directory in `client`. 

There are multiple options that can be set currently, **but none of them do anything** except the active/inactive toggle:
![bild](https://user-images.githubusercontent.com/110222/70054063-0ee10000-15d7-11ea-972f-fc5ad8d6bcde.png)

# Proposed fix
1. Remove unused options in `admin`
1. Add some more options that OpenLayers exposes, so e.g. color of selection can be configured

**Comment by jacobwod** [comment]
Here's the result, hope you like it:
![bild](https://user-images.githubusercontent.com/110222/70057202-0ab7e100-15dd-11ea-8b92-27a0355ce543.png)

**Comment by sweco-semara** [comment]
The coordinates plug-in currently suffers from some hardcoded defaults e.g. icon scale and would also need this kind of flexibility in Hajk's admin offered by the fix for this issue, I have added to our backlog to contribute an improvement inspired by [the fix for this issue](https://github.com/sweco-se/hajk-fork/commit/77ff5e2744f94d192ff472cf28dd0c72986272d8).

**Comment by jacobwod** [comment]
Looks good @sweco-semara. Feel free to PR when ready. 👍
