### ISSUE TITLE
Anchor-plugin not updating z-value when using scroll to zoom

### ISSUE THREAD

**Issue by sweco-seqtob** [hajkmap/Hajk#523]
Then event "mapUpdated" is not fired in AnchorModel.js when using scroll to zoom in map. 
The result is a non-updated z-value for AnchorPlugin.

The two following events is not fired when user uses MouseWheel to scroll in map and therefore
the publish of "mapUpdated" is not fired.
```
this.map.getView().on("change:resolution", update);
this.map.getView().on("change:center", update);
```

There is no out-of-the-box-event to capture this and a possible solution is:

```
var currZoom = map.getView().getZoom();
map.on('moveend', function(e) {
  var newZoom = map.getView().getZoom();
  if (currZoom != newZoom) {
    console.log('zoom end, new zoom: ' + newZoom);
    currZoom = newZoom;
  }
});
```
From : https://gis.stackexchange.com/questions/309387/how-to-detect-zoom-change-in-openlayers/309404

**Comment by jacobwod** [comment]
I found another way of solving this: the reason it didn't work previously was that we were ignoring events that had `getInteracting() === true`. Now, obviously when user scrolls, that was seen as interacting, so that property _was_ true and we ignored updating the anchor.

Now I've removed it and done some more cleanups in `AnchorModel.js`. Let's see if it works. We can always revert and go with the solution you mention, which indeed works (I tested it first, before I realized I could simplify existing code).
