### ISSUE TITLE
Collector: Allow users to insert multiple geometries in the same feedback

### ISSUE THREAD

**Issue by hitomin21** [hajkmap/Hajk#615]
Users are limited to only providing one geometry per feedback. So if an user wants to give the same feedback about n areas, it needs to create n feedbacks.

Currently, the answers are inserted into a geometry which is placed in the database. Instead, we should create WKTs from the geometries that the user placed for the feedback. We can then have multiple questions where the user can specify geometries instead of only one.

Putting several separate feedback features in the database would create an issue if linking these back when displaying  the answers to the administrators. I think the WKT approach where everything is stored in one feature is preferred.

**Comment by perosoderstrom** [comment]
Hi Hitomi!
We use the feedback information in the database in a task management system, so the WKT solution will cause problems for us. 
We also think it is generally best so store information in a database rather than in files. 
A solution might be to store the feedback information in one table, and the geometry/geometries in another table and joining them by common id:s in a view.

**Comment by hitomin21** [comment]
Hi,

I know Mattias contacted you Per but I will write here so everyone can see the answer.

The new functionality has to be enabled in the config. Otherwise the tool will continue to work as it did previously. The idea is that WKT should be used to put the WKT strings into different columns in the same database row. No information is stored in files in the solution I implemented.

**Comment by persoderstrom** [comment]
Hi!
Good @hitomin21! 
Now I know how the purpose of WKT and that it is configurable.

**Comment by hitomin21** [comment]
Feature has been merged into develop
