### ISSUE TITLE
Provide demo site or docker container

### ISSUE THREAD

**Issue by ThomasHalwax** [hajkmap/Hajk#660]
Hi,

I'd love to try Hajk but I failed to get it running using the provided information. So it would be great if you could provide either a live demo site or a Docker container (at least a Dockerfile).

Thank you very much,
Thomas

**Comment by jacobwod** [comment]
Thank you for the suggestion. At the moment, none of the developers have the time to create a Docker container, but we do have it as a long-term goal.

In the meantime you have a couple of options. If you just want to see a running version of Hajk, you can take a look at e.g. Halmstad's map (https://karta.halmstad.se). Please note that this is not a full-fledged demo, but rather a running production app. 

I'd like to suggest that you try the new NodeJS-version of the backend. See installation [instructions here](https://github.com/hajkmap/Hajk/tree/master/new-backend). If you just want to run everything locally it should be as easy as 
- cloning the repo
- go to each and every of the following directories: `new-backend`, `new-client`, `new-admin`
- in each of them, do `npm install && npm start`

This should get you going with the backend running on `localhost:3002`, while client and admin on ports 3000 and 3001. You will probably need to tweak some settings in `new-client/public/appConfig.json` so that the client application can find your backend (running on localhost:3002). 

Give it a try and feel free to report your progress.

**Comment by ThomasHalwax** [comment]
@jacobwod Thank you for your response. I was not aware of https://karta.halmstad.se. I think this will do for now to get some impressions about Hajk :-)

**Comment by matself** [comment]
Hi Thomas! I am not sure what installation instructions you have tried, but this may help.
There is a compiled release (March 2020) here (scroll to the bottom of the page).
https://github.com/hajkmap/Hajk/releases/tag/v3.2.0
Installation and configuration instructions are here. In Swedish only though, and explicitly valid for HAJK 2. I have been unable to get confirmation that they are valid for the current HAJK 3. However, the last time I set up a HAJK instance they worked. But that was the previous HAJK 3 release.
https://github.com/hajkmap/Hajk/blob/master/HAJK2_README.md

**Comment by jacobwod** [comment]
I've just reviewed the instructions on the project's main page. Please just use that instead. https://internkarta.halmstad.se/?m=bmf_bygglov&x=95600&y=6287796&z=0

As for the 3.2 release: it's almost a year old and there've been so many improvements to the project since, that I see no reason for downloading that release. Just go with whatever's in `master`. 👍

**Comment by matself** [comment]
I agree that 3.2 is old, but it is still the latest release. An update would be welcome. Not sure where the new instructions are, though. Your link was internal. Specifically, the IIS configurations are important.

**Comment by jacobwod** [comment]
Thanks, I've updated the link in my previous post.

**Comment by jacobwod** [comment]
Final note: an automatic build that always compiles the latest code in _master_ can now be found here: http://hajk-demo.netlify.app.
