### ISSUE TITLE
Use colors from palette instead of hard-coded values

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#674]
A quick try-out of DocumentHandler renders this result:
![Skärmavbild 2021-02-17 kl  13 02 01](https://user-images.githubusercontent.com/110222/108201946-b9800880-7120-11eb-8ce1-b8435ab4ad5f.png)

**Please stop using hard-coded values.** In this case, I think that something like `theme.palette.active` or similar would do just as fine.

(Ping @sweco-secoma as I noticed that you're assigned to other the remaing DocumentHandler bugs.)

**Comment by sweco-secoma** [comment]
Hej Jacob,

OK tack, vi tar med den i sprinten.

/Matt

Från: Jacob Wodzyński <notifications@github.com>
Skickat: den 17 februari 2021 13:08
Till: hajkmap/Hajk <Hajk@noreply.github.com>
Kopia: Corney, Matthew <matthew.corney@sweco.se>; Mention <mention@noreply.github.com>
Ämne: [hajkmap/Hajk] Use colors from palette instead of hard-coded values (#674)


A quick try-out of DocumentHandler renders this result:
[Skärmavbild 2021-02-17 kl  13 02 01]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/110222/108201946-b9800880-7120-11eb-8ce1-b8435ab4ad5f.png__;!!HBVxBjZwpQ!lqck7VOdW7u7zCqpihDlosipG6btnpcc2vqtI95YR61fMQTaS73tMLwWKzaCMWEK2ii_aA$>

Please stop using hard-coded values. In this case, I think that something like theme.palette.active or similar would do just as fine.

(Ping @sweco-secoma<https://urldefense.com/v3/__https:/github.com/sweco-secoma__;!!HBVxBjZwpQ!lqck7VOdW7u7zCqpihDlosipG6btnpcc2vqtI95YR61fMQTaS73tMLwWKzaCMWGVF1qR1Q$> as I noticed that you're assigned to other the remaing DocumentHandler bugs.)

**Comment by sweco-secoma** [comment]
This is fixed (although not in master yet) for the table of contents. Change still needed for default colors for 'faktarutor'.

**Comment by jacobwod** [comment]
OK, let's leave it as-is for now until the last change is pushed as well, then close.

**Comment by sweco-seqtob** [comment]
Fixed this in dop/develop, are going to discuss colors picked at next meeting. Might change colors but the logic is there

**Comment by jacobwod** [comment]
I think I lost track of this as you've probably handled this via Jira. Can you confirm if it's merged (to `develop`) and can be closed?

**Comment by sweco-secoma** [comment]
Hi, yep it came in to develop as a part of  [#eaceddd](https://github.com/hajkmap/Hajk/commit/eacedddd13655718fb768c9161626fe1c233fac7)
