### ISSUE TITLE
Interface of API doc generation not defined in new-client

### ISSUE THREAD

**Issue by UniverseFly** [hajkmap/Hajk#718]
As described in [this](https://github.com/vinitshahdeo/ParkingLot/issues/2) issue, API documentation can be updated simply through `npm run createdocs`. But in the latest version, the option `createdocs` is missing from the `package.json` configuration file. Is this a mistake or on intention?

**Comment by jacobwod** [comment]
That's correct, the `script` responsible for creation of JSdoc, as well as the dependency (`jsdoc`) have been removed from `package.json` recently. The reason is that the code was lacking sufficient comments for the time being. Our goal is to improve the comments and re-introduce JSdoc at some point in the future.
