### ISSUE TITLE
Separate "Lås zoom till satta upplösningar" for desktop and mobile version

### ISSUE THREAD

**Issue by hitomin21** [hajkmap/Hajk#840]
Currently, it is possible to limit the map to specified zoom levels using the setting "Lås zoom till satta upplösningar". This works well for normal computers but not so well for smartphones where the users are using pinch zoom.

It would be better if there were two settings:
"Lås zoom till satta upplösningar - Datorer"
and 
"Lås zoom till satta upplösningar - Mobiler"

so it is possible to configure separately.

**Comment by hitomin21** [comment]
@jacobwod : I wonder if this code can be removed without causing issues, sorry to ask you about code you wrote a long time ago. Do you remember why it was added?

https://github.com/hajkmap/Hajk/blob/70f08d69bc38892a47e1866a155268acbb3706c2/new-client/src/models/layers/WMTSLayer.js#L87-L97

Currently, it overwrites the settings we put in admin for resolutions, zoom, etc. so I would like to remove updateMapViewResolutions to prevent the original View from being removed.

**Comment by jacobwod** [comment]
@hitomin21 Well, it's problematic as **without this, you must ensure that the WMTS grid aligns with your Map's grid**. You can control it if you control the WMTS source, but otherwise you should adjust the map after the WMTS's grid. 

So what this code does is to **ensure that we tell the Map (or, rather the `ol.View`) which resolutions to use**. 

There is a big issue with this method however: this runs for each WMTS layer, but we only have one View! So the most recently added WMTS layer "wins" as it gets its desired resolutions into the View. The other WMTS layer will become broken. 

So there's a bigger question here: how can we make sure that WMTS layers with different gridsets are added to the same View and work correctly?
