### ISSUE TITLE
Don't zoom in when drawing a search polygon

### ISSUE THREAD

**Issue by jacobwod** [hajkmap/Hajk#902]
Currently there's a bug in the spatial search tool that will zoom in on the map when user double-clicks (which is the way to end drawing a polygon). We don't want the zoom event to occur.

**Comment by Hallbergs** [comment]
This issue is a bit interesting... In the FmeServer-plugin the clicks are stopped without issues when stopClick is set to true. (StopClick is a setting in the draw constructor). But in the search plugin they are not. My guess is that we're dealing with a timing issue (in the FmeServer-plugin we have some logic running in the drawend-event which seems to run long enough to give the draw interaction enough time to stop the clicks).

@sweco-secoma @sweco-semara I saw that you were dealing with a similar issue in the geoSuite-plugin. Not sure this solution is better than yours, but i thought i should let you know how we fixed it in the search plugin anyways :)

**Comment by jacobwod** [comment]
`setTimeout(() => { … }, 1);` is less code. Less code is better. 👍

**Comment by Hallbergs** [comment]
But random timeouts throughout the application is scary :hushed:

**Comment by jacobwod** [comment]
This is not random, it's _exactly_ 1 ms! 😉

**Comment by sweco-secoma** [comment]
Hi @Hallbergs , thanks for noticing and letting me know. Will be working on that next week so will see that i update it then. I think I had a comment there to look if there as a better way, so the suggestion is very welcome.
